version: 2
jobs:
  build:
    working_directory: /root/oi-lang
    docker:
      - image: wolverian/oi-lang
    steps:
      - run:
          name: Install Leiningen
          command: |
            wget -q https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
            chmod +x lein
      - checkout
      - run:
          name: Install karma
          command: npm install karma-cli -g
      - run:
          name: Tests
          command: env PATH=..:$PATH make test
      - run:
          name: Lint
          command: env PATH=..:$PATH make lint
      - store_test_results:
          path: run/compiled/karma/test/junit/karma

