version: 2
jobs:
  build:
    working_directory: /root/oi-lang
    docker:
      - image: node:latest
    steps:
      - run: apt update && apt full-upgrade -y && apt install -y openjdk-7-jdk
      - run: wget -q https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod +x lein
      - checkout
      - run: npm install karma-cli -g
      - run: env PATH=.:$PATH make test
      - run: env PATH=.:$PATH make lint
      - store_test_results:
          path: run/compiled/karma/test/junit/karma

