version: 2
jobs:
  build:
    working_directory: /root/oi-lang
    docker:
      - image: node:latest
    steps:
      - run: apt update && apt full-upgrade && apt install -y openjdk-7-jdk
      - run: cd /tmp && wget -q https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run: cd /tmp && wget -q https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod +x lein
      - checkout
      - run: /tmp/lein deps
      - run: env PATH=/tmp/phantomjs-2.1.1-linux-x86_64/bin:$PATH /tmp/lein karma-once
      - store_test_results:
          path: run/compiled/karma/test/junit/karma

