version: 2
jobs:
    build:
        working_directory: /root/oi-lang
        docker:
            - image: clojure
        steps:
            - run: wget -q https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            - run: tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
            - checkout
            - run: lein deps
            - run: env PATH=phantomjs-2.1.1-linux-x86_64/bin:$PATH lein doo phantom test once

