version: 2
jobs:
    build:
        working_directory: /root/oi-lang
        docker:
            - image: lein
        steps:
            - checkout
            - run: lein deps
            - run: lein doo phantom test once

