version: 2
jobs:
  build:
    working_directory: /home/oi/oi-lang
    docker:
      - image: wolverian/oi-lang:0.0.1
        environment: 
          LEIN_ROOT: 1
    steps:
      - run:
          name: Install Leiningen
          command: |
            mkdir -p /root/bin
            cd /root/bin
            wget -q https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
            chmod +x lein
      - run:
          name: Install karma
          command: npm install karma-cli -g
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "project.clj" }}
      - run:
          name: Dependencies
          command: env PATH=$HOME/bin:$PATH lein deps
      - run:
          name: Tests
          command: env PATH=$HOME/bin:$PATH make test
      - run:
          name: Lint
          command: env PATH=$HOME/bin:$PATH make lint
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "project.clj" }}-{{ checksum "/root/bin/lein" }}
          paths:
            - "node_modules"
            - "~/.m2"
            - "~/.lein"
      - store_test_results:
          path: test-results/

